ALTER TABLE "Team" ADD COLUMN "tag" TEXT;
ALTER TABLE "Team" ADD COLUMN "bannerUrl" TEXT;
ALTER TABLE "Team" ADD COLUMN "videoUrl" TEXT;
ALTER TABLE "Team" ADD COLUMN "contactUrl" TEXT;
ALTER TABLE "Team" ADD COLUMN "region" TEXT;
ALTER TABLE "Team" ADD COLUMN "language" TEXT;
ALTER TABLE "Team" ADD COLUMN "playstyle" TEXT;
ALTER TABLE "Team" ADD COLUMN "goals" TEXT;
ALTER TABLE "Team" ADD COLUMN "recruitmentStatus" TEXT NOT NULL DEFAULT 'OPEN';