/** Compact OpenDota hero id → api slug + RU label for bracket matchup thumbs. */
export type DotaHeroMeta = { id: number; slug: string; name: string };

export const DOTA_HERO_META: DotaHeroMeta[] = [
	{ id: 1, slug: 'antimage', name: 'Anti-Mage' },
	{ id: 2, slug: 'axe', name: 'Axe' },
	{ id: 3, slug: 'bane', name: 'Bane' },
	{ id: 4, slug: 'bloodseeker', name: 'Bloodseeker' },
	{ id: 5, slug: 'crystal_maiden', name: 'Crystal Maiden' },
	{ id: 6, slug: 'drow_ranger', name: 'Drow Ranger' },
	{ id: 7, slug: 'earthshaker', name: 'Earthshaker' },
	{ id: 8, slug: 'juggernaut', name: 'Juggernaut' },
	{ id: 9, slug: 'mirana', name: 'Mirana' },
	{ id: 10, slug: 'morphling', name: 'Morphling' },
	{ id: 11, slug: 'nevermore', name: 'Shadow Fiend' },
	{ id: 12, slug: 'phantom_lancer', name: 'Phantom Lancer' },
	{ id: 13, slug: 'puck', name: 'Puck' },
	{ id: 14, slug: 'pudge', name: 'Pudge' },
	{ id: 15, slug: 'razor', name: 'Razor' },
	{ id: 16, slug: 'sand_king', name: 'Sand King' },
	{ id: 17, slug: 'storm_spirit', name: 'Storm Spirit' },
	{ id: 18, slug: 'sven', name: 'Sven' },
	{ id: 19, slug: 'tiny', name: 'Tiny' },
	{ id: 20, slug: 'vengefulspirit', name: 'Vengeful Spirit' },
	{ id: 21, slug: 'windrunner', name: 'Windranger' },
	{ id: 22, slug: 'zuus', name: 'Zeus' },
	{ id: 23, slug: 'kunkka', name: 'Kunkka' },
	{ id: 25, slug: 'lina', name: 'Lina' },
	{ id: 26, slug: 'lion', name: 'Lion' },
	{ id: 27, slug: 'shadow_shaman', name: 'Shadow Shaman' },
	{ id: 28, slug: 'slardar', name: 'Slardar' },
	{ id: 29, slug: 'tidehunter', name: 'Tidehunter' },
	{ id: 30, slug: 'witch_doctor', name: 'Witch Doctor' },
	{ id: 31, slug: 'lich', name: 'Lich' },
	{ id: 32, slug: 'riki', name: 'Riki' },
	{ id: 33, slug: 'enigma', name: 'Enigma' },
	{ id: 34, slug: 'tinker', name: 'Tinker' },
	{ id: 35, slug: 'sniper', name: 'Sniper' },
	{ id: 36, slug: 'necrolyte', name: 'Necrophos' },
	{ id: 37, slug: 'warlock', name: 'Warlock' },
	{ id: 38, slug: 'beastmaster', name: 'Beastmaster' },
	{ id: 39, slug: 'queenofpain', name: 'Queen of Pain' },
	{ id: 40, slug: 'venomancer', name: 'Venomancer' },
	{ id: 41, slug: 'faceless_void', name: 'Faceless Void' },
	{ id: 42, slug: 'skeleton_king', name: 'Wraith King' },
	{ id: 43, slug: 'death_prophet', name: 'Death Prophet' },
	{ id: 44, slug: 'phantom_assassin', name: 'Phantom Assassin' },
	{ id: 45, slug: 'pugna', name: 'Pugna' },
	{ id: 46, slug: 'templar_assassin', name: 'Templar Assassin' },
	{ id: 47, slug: 'viper', name: 'Viper' },
	{ id: 48, slug: 'luna', name: 'Luna' },
	{ id: 49, slug: 'dragon_knight', name: 'Dragon Knight' },
	{ id: 50, slug: 'dazzle', name: 'Dazzle' },
	{ id: 51, slug: 'rattletrap', name: 'Clockwerk' },
	{ id: 52, slug: 'leshrac', name: 'Leshrac' },
	{ id: 53, slug: 'furion', name: "Nature's Prophet" },
	{ id: 54, slug: 'life_stealer', name: 'Lifestealer' },
	{ id: 55, slug: 'dark_seer', name: 'Dark Seer' },
	{ id: 56, slug: 'clinkz', name: 'Clinkz' },
	{ id: 57, slug: 'omniknight', name: 'Omniknight' },
	{ id: 58, slug: 'enchantress', name: 'Enchantress' },
	{ id: 59, slug: 'huskar', name: 'Huskar' },
	{ id: 60, slug: 'night_stalker', name: 'Night Stalker' },
	{ id: 61, slug: 'broodmother', name: 'Broodmother' },
	{ id: 62, slug: 'bounty_hunter', name: 'Bounty Hunter' },
	{ id: 63, slug: 'weaver', name: 'Weaver' },
	{ id: 64, slug: 'jakiro', name: 'Jakiro' },
	{ id: 65, slug: 'batrider', name: 'Batrider' },
	{ id: 66, slug: 'chen', name: 'Chen' },
	{ id: 67, slug: 'spectre', name: 'Spectre' },
	{ id: 68, slug: 'ancient_apparition', name: 'Ancient Apparition' },
	{ id: 69, slug: 'doom_bringer', name: 'Doom' },
	{ id: 70, slug: 'ursa', name: 'Ursa' },
	{ id: 71, slug: 'spirit_breaker', name: 'Spirit Breaker' },
	{ id: 72, slug: 'gyrocopter', name: 'Gyrocopter' },
	{ id: 73, slug: 'alchemist', name: 'Alchemist' },
	{ id: 74, slug: 'invoker', name: 'Invoker' },
	{ id: 75, slug: 'silencer', name: 'Silencer' },
	{ id: 76, slug: 'obsidian_destroyer', name: 'Outworld Destroyer' },
	{ id: 77, slug: 'lycan', name: 'Lycan' },
	{ id: 78, slug: 'brewmaster', name: 'Brewmaster' },
	{ id: 79, slug: 'shadow_demon', name: 'Shadow Demon' },
	{ id: 80, slug: 'lone_druid', name: 'Lone Druid' },
	{ id: 81, slug: 'chaos_knight', name: 'Chaos Knight' },
	{ id: 82, slug: 'meepo', name: 'Meepo' },
	{ id: 83, slug: 'treant', name: 'Treant Protector' },
	{ id: 84, slug: 'ogre_magi', name: 'Ogre Magi' },
	{ id: 85, slug: 'undying', name: 'Undying' },
	{ id: 86, slug: 'rubick', name: 'Rubick' },
	{ id: 87, slug: 'disruptor', name: 'Disruptor' },
	{ id: 88, slug: 'nyx_assassin', name: 'Nyx Assassin' },
	{ id: 89, slug: 'naga_siren', name: 'Naga Siren' },
	{ id: 90, slug: 'keeper_of_the_light', name: 'Keeper of the Light' },
	{ id: 91, slug: 'wisp', name: 'Io' },
	{ id: 92, slug: 'visage', name: 'Visage' },
	{ id: 93, slug: 'slark', name: 'Slark' },
	{ id: 94, slug: 'medusa', name: 'Medusa' },
	{ id: 95, slug: 'troll_warlord', name: 'Troll Warlord' },
	{ id: 96, slug: 'centaur', name: 'Centaur Warrunner' },
	{ id: 97, slug: 'magnataur', name: 'Magnus' },
	{ id: 98, slug: 'shredder', name: 'Timbersaw' },
	{ id: 99, slug: 'bristleback', name: 'Bristleback' },
	{ id: 100, slug: 'tusk', name: 'Tusk' },
	{ id: 101, slug: 'skywrath_mage', name: 'Skywrath Mage' },
	{ id: 102, slug: 'abaddon', name: 'Abaddon' },
	{ id: 103, slug: 'elder_titan', name: 'Elder Titan' },
	{ id: 104, slug: 'legion_commander', name: 'Legion Commander' },
	{ id: 105, slug: 'techies', name: 'Techies' },
	{ id: 106, slug: 'ember_spirit', name: 'Ember Spirit' },
	{ id: 107, slug: 'earth_spirit', name: 'Earth Spirit' },
	{ id: 108, slug: 'abyssal_underlord', name: 'Underlord' },
	{ id: 109, slug: 'terrorblade', name: 'Terrorblade' },
	{ id: 110, slug: 'phoenix', name: 'Phoenix' },
	{ id: 111, slug: 'oracle', name: 'Oracle' },
	{ id: 112, slug: 'winter_wyvern', name: 'Winter Wyvern' },
	{ id: 113, slug: 'arc_warden', name: 'Arc Warden' },
	{ id: 114, slug: 'monkey_king', name: 'Monkey King' },
	{ id: 119, slug: 'dark_willow', name: 'Dark Willow' },
	{ id: 120, slug: 'pangolier', name: 'Pangolier' },
	{ id: 121, slug: 'grimstroke', name: 'Grimstroke' },
	{ id: 123, slug: 'hoodwink', name: 'Hoodwink' },
	{ id: 126, slug: 'void_spirit', name: 'Void Spirit' },
	{ id: 128, slug: 'snapfire', name: 'Snapfire' },
	{ id: 129, slug: 'mars', name: 'Mars' },
	{ id: 135, slug: 'dawnbreaker', name: 'Dawnbreaker' },
	{ id: 136, slug: 'marci', name: 'Marci' },
	{ id: 137, slug: 'primal_beast', name: 'Primal Beast' },
	{ id: 138, slug: 'muerta', name: 'Muerta' },
	{ id: 145, slug: 'ringmaster', name: 'Ringmaster' },
	{ id: 146, slug: 'kez', name: 'Kez' }
];

const byId = new Map(DOTA_HERO_META.map((h) => [h.id, h]));

export function dotaHeroMeta(heroId: number): DotaHeroMeta | null {
	return byId.get(heroId) ?? null;
}

export function dotaHeroApiName(heroId: number): string | null {
	const meta = byId.get(heroId);
	return meta ? `npc_dota_hero_${meta.slug}` : null;
}

/** Local landscape thumb for bracket matchup chips. */
export function dotaHeroThumb(heroId: number): { name: string; image: string } | null {
	const meta = byId.get(heroId);
	if (!meta) return null;
	return { name: meta.name, image: `/heroes/${meta.slug}.webp` };
}
